<!-- BEGIN CONTENT-->
			<div id="content">

				<!-- BEGIN BLANK SECTION -->
				<section>
					<div class="section-header">
						<ol class="breadcrumb">
							<li><a href="../../html/.html">home</a></li>
							<li class="active">Blank page</li>
						</ol>
					</div><!--end .section-header -->
					<div class="section-body">
						<h1>Testing</h1>
						<!-- BEGIN COLORS -->
						<div class="row">
							<div class="col-lg-12">
								<h4>Colors</h4>
							</div><!--end .col -->
							<div class="col-lg-3 col-md-4">
								<article class="margin-bottom-xxl">
									<p>
										Every color that is available for a card, is also available for an off-canvas.
									</p>
								</article>
							</div><!--end .col -->
							<div class="col-lg-offset-1 col-md-8">
								<div class="card">
									<div class="card-body">
										<a class="btn btn-raised ink-reaction btn-primary" href="#offcanvas-demo-color1" data-toggle="offcanvas" data-backdrop="false">Color 1</a>
										<a class="btn btn-raised ink-reaction btn-accent-dark" href="#offcanvas-demo-color2" data-toggle="offcanvas" data-backdrop="false">Color 2</a>
										<a class="btn btn-raised ink-reaction btn-info" href="#offcanvas-demo-color3" data-toggle="offcanvas" data-backdrop="false">Color 3</a>
										<a class="btn btn-raised ink-reaction btn-default-dark" href="#offcanvas-demo-color4" data-toggle="offcanvas" data-backdrop="false">Color 4</a>
									</div><!--end .card-body -->
								</div><!--end .card -->
								<em class="text-caption">Basic headings</em>
							</div><!--end .col -->
						</div><!--end .row -->
						<!-- END COLORS -->
					</div><!--end .section-body -->
				</section>

				<!-- BEGIN BLANK SECTION -->
				
			</div><!--end #content-->
			<!-- END CONTENT -->